import{buildBoardScene}from"/src/trace-layout.mjs";
const EXAMPLES={steady:"/examples/steady.json",review:"/examples/human-review.json"},COLORS={code:"#69a7ff",judgment:"#9c7cff",policy:"#f0b75f",review:"#ff8d6b",branch:"#65d6a6"},state={trace:null,scene:null,index:-1,timer:null},$=id=>document.getElementById(id),svg=$("board");
function el(name,attrs={}){const n=document.createElementNS("http://www.w3.org/2000/svg",name);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,String(v));return n}
function fmt(step){const s=step?.summary||{};if(s.primitive==="noul"&&Number.isFinite(s.answer))return s.answer.toFixed(2);if(s.topLevel)return s.topLevel;if(s.answer!=null)return String(s.answer);if(s.scenarioId)return s.scenarioId;return"—"}
function probabilities(step){const root=$("probabilities"),p=step?.summary?.probabilities;if(!p){root.innerHTML='<p class="muted small">Shown for judgment pegs.</p>';return}root.innerHTML=Object.entries(p).sort((a,b)=>b[1]-a[1]).map(([k,v])=>'<div class="prob-row"><span>'+k+'</span><div class="track"><div class="fill" style="width:'+Math.round(v*100)+'%"></div></div><strong>'+Math.round(v*100)+'%</strong></div>').join("")}
function inspect(i){const p=state.scene?.semanticPegs[i];if(!p){$("pegTitle").textContent="Drop the ball";$("pegNote").textContent="Step through the semantic trace.";["kind","answer","confidence","route"].forEach(id=>$(id).textContent="—");probabilities(null);return}$("pegTitle").textContent=p.label;$("pegNote").textContent=p.kindLabel+" · "+p.nodeId;$("kind").textContent=p.kind;$("answer").textContent=fmt(p);$("confidence").textContent=Number.isFinite(p.summary?.confidence)?p.summary.confidence.toFixed(2):"—";$("route").textContent=p.routeTo||"terminal";probabilities(p)}
function render(){const s=state.scene;svg.setAttribute("viewBox","0 0 "+s.width+" "+s.height);svg.replaceChildren();for(let n=-2;n<=2;n++){const x=s.width/2+n*92;svg.append(el("line",{x1:x,x2:x,y1:55,y2:s.height-44,class:"guide"}));const t=el("text",{x,y:s.height-20,"text-anchor":"middle",class:"guide-label"});t.textContent=n===0?"μ":(n>0?"+":"")+n+"σ";svg.append(t)}s.cosmeticPegs.forEach(p=>svg.append(el("circle",{cx:p.x,cy:p.y,r:2.3,class:"decor"})));if(s.path.length>1){const d=s.path.map((p,i)=>(i?"L ":"M ")+p.x+" "+p.y).join(" ");svg.append(el("path",{d,class:"path"}))}s.semanticPegs.forEach((p,i)=>{const halo=el("circle",{cx:p.x,cy:p.y,r:i<=state.index?18:13,class:"halo",stroke:COLORS[p.kind]||"#fff"});halo.style.opacity=i<=state.index?".22":".06";svg.append(halo);const dot=el("circle",{cx:p.x,cy:p.y,r:i<=state.index?9:6,class:"semantic "+p.kind});dot.style.opacity=i<=state.index?"1":".38";dot.style.cursor="pointer";dot.addEventListener("click",()=>{state.index=i;inspect(i);render()});svg.append(dot);const label=el("text",{x:p.x+14,y:p.y-11,class:"peg-label"});label.textContent=p.sequence+". "+p.kindLabel;label.style.opacity=i<=state.index?"1":".32";svg.append(label)});if(state.index>=0){const p=s.semanticPegs[state.index];svg.append(el("circle",{cx:p.x,cy:p.y,r:7,class:"ball"}))}}
function stop(){if(state.timer)clearInterval(state.timer);state.timer=null;$("play").textContent="▶ Sigma Drop"}function reset(){stop();state.index=-1;inspect(-1);render()}function step(){const max=state.scene.semanticPegs.length-1;if(state.index>=max)state.index=-1;state.index++;inspect(state.index);render();if(state.index>=max)stop()}function play(){reset();$("play").textContent="⏸ Pause";step();state.timer=setInterval(step,650)}
async function load(key){stop();const r=await fetch(EXAMPLES[key]);state.trace=await r.json();state.scene=buildBoardScene(state.trace);state.index=-1;$("title").textContent=state.trace.title||state.trace.traceId;$("status").textContent=state.trace.status;$("terminal").textContent=state.trace.terminalScenario||"waiting for human";const d=state.scene.deviation;$("sigma").textContent=d?(d.value>=0?"+":"")+d.value.toFixed(2)+"σ":"—";inspect(-1);render()}
$("example").addEventListener("change",e=>load(e.target.value));$("play").addEventListener("click",()=>state.timer?stop():play());$("step").addEventListener("click",()=>{stop();step()});$("reset").addEventListener("click",reset);load("steady").catch(console.error);
